
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - synopsys.com
  resources:
  - blackducks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synopsys.com
  resources:
  - blackducks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - synopsys.com
  resources:
  - opssights
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - synopsys.com
  resources:
  - opssights/status
  verbs:
  - get
  - patch
  - update
